language: java

sudo: false

matrix:
  include:
   - os: linux
     env: MAVEN_PROFILE=""
     jdk: oraclejdk8
     addons:
       apt:
         packages:
           - gcc-multilib
   - os: linux
     # Travis by default is 64 bit so we toggle to use the 32 bit libs
     env: MAVEN_PROFILE="-Plinux32,-linux64"
     jdk: oraclejdk8
     addons:
       apt:
         packages:
           - gcc-multilib
   - os: linux
     env: MAVEN_PROFILE=""
     jdk: openjdk7
     addons:
       apt:
         packages:
           - gcc-multilib
   - os: linux
     # Travis by default is 64 bit so we toggle to use the 32 bit libs
     env: MAVEN_PROFILE="-Plinux32,-linux64"
     jdk: openjdk7
     addons:
       apt:
         packages:
           - gcc-multilib
   # Travis only supports jdk7 on OS X at the moment (and needs JAVA_HOME set)
   - os: osx
     env: JAVA_HOME=$(/usr/libexec/java_home)

script:
  - mvn install $MAVEN_PROFILE

notifications:
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_failure: change
    on_success: change

deploy:
  provider: s3
  access_key_id:
    secure: mzocVkJlpS0JPwFCCTtodPTkO8O5e/N++JraB3nzJnArCqevZHxdI9LauqqeZ5On/SMpvhrEsU/dHvP1+2la0CXUHd11tmTWxWeL96yyxiSaseedhb/jFGzmESrzXIV+gxOh6jqRP257PeM2DONhlf6C9T099cMMx7Z7jUxuGTmzZKCeSZVq7UrfypNbJUZJaSsf7CmQmgJ4iS+ojKCgA8rni1ptP1UOD6PmX2dqnH1dVz8uQ3W1B0IcHqvkF8KCL5Rtds7ajH4hSt/M6ywZgm818DA6f9gqG+fsEe4otYqjdLEZw0asN286RP01RjovYBjcJ3e2PH99LWAoZgih9VnXGuma9ZyCpC1tyvTF0B79eFgosi4vfayYxn0a67bsnLdd0hosjXq91lnIlWFfPYrllPOKnU1Wn54PwULJzQDL1TSrhv6n0tb27L7D6Ix2RLm0MLJdSO96tu/j68o4AwAbacDmomPKEzVsqcjHI9l1J8R2TCzZHR+W4nNDHwXX0JpppNQb2OCAQzbb6cK0Zj7seiHyZH41/R3/3HO1GULVeW1L/AVK/OIsdDcYRJ7vIBnnIi3lFj1iVKW6Z0xLCxyUvYcTpVpgi5SMaC0GAIzJtKA3G9JV8H2dgLqgKdMX+eFdydVfKKrf2qZtQmgYL6KL+VLwbsXUwe5kjaHGhNY=
  secret_access_key:
    secure: LkvGtNFlxeSkCbl3ln9KKO3Si+ihKqOTNLiCsD60ZXeGwoMwUvgDyda+L4fDAdrCURRGMYkxCpi4cTKTjr8ppxUu7kHYaCJS6NJSIDatOu717FP/c0FBjnPTL5VRJ47hiF85i8ryTYTfXd1PagK11tY5sPvWZNfIikeBg1ZS0DkEBPyfSjlkx+9BBN84KVuLWbvjjhrdXWI6V1Bq+1gSZWU0Cqo2j4n3nTBBij9H6YmDzyHmv+ymJxsG2V9xlm5af4rYfaPin7li2qIMF6VcRTsIdspy63GPhZn7ovQFK/9uLf3jA2wkHaX962Oom/z5ZZfEwfdoLku5spWAzvfXU2zybwQPwYLb7EwhZU1bSBEkYpmcsPlLbQEIU5PFjIrrEfE4n4PF2cmKizrwwaitL7MZMsxSOFSx0xKfNwvG+dzUo0dmOav7KnDujTR5OYTLw+ghbdZpTzCpFwsec94ybdMND2EV7Dx7XjxHeLXq86Qdw8d/ncjsPNyWl9cMUAGU5liivp4mAh1inmdTtyNLBe26GL6kCoTe2MEPIOgSQlkCA2yhJoXIDQXpQqd3Lnwi0eAZWV0n2rht+Oy4bmHcvdyIE9Q/cJ/SVrkO0IUSNKALBNuqzBv+EMNUUrXq1+4Y7RrXFmUjjvkR9Hx3RTxgco+6JbV8vD13iiQHICnAKYs=
  bucket: cmake-builds
  skip_cleanup: true
  local_dir: cmake-binaries/target
  on:
    branch: staging
