language: java

sudo: false

matrix:
  include:
   - os: linux
     jdk: oraclejdk8
     addons:
       apt:
         packages:
           - gcc-multilib
   - os: linux
     # Travis by default is 64 bit so we toggle to use the 32 bit libs
     env: MAVEN_PROFILE="-DosDetection=false -Plinux-i386"
     jdk: oraclejdk8
     addons:
       apt:
         packages:
           - cmake
           - gcc-multilib
   # Travis only supports jdk7 on OS X at the moment (and needs JAVA_HOME set)
   - os: osx
     env: JAVA_HOME=$(/usr/libexec/java_home)

install: true
script:
  - mvn install $MAVEN_PROFILE

notifications:
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_failure: change
    on_success: change
